[build]
  # Commande de build pour Create React App avec CI=false pour ignorer les warnings
  command = "CI=false npm run build"
  
  # Dossier de sortie du build
  publish = "build"
  
  # Variables d'environnement pour le build
  environment = { NODE_VERSION = "18", CI = "false" }

[build.processing]
  # Optimisation des images
  skip_processing = false

[build.processing.css]
  # Minification CSS
  bundle = true
  minify = true

[build.processing.js]
  # Minification JavaScript
  bundle = true
  minify = true

[build.processing.html]
  # Optimisation HTML
  pretty_urls = true

[build.processing.images]
  # Compression d'images automatique
  compress = true

# Redirections pour SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité et performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Cache pour les assets statiques
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache pour les fichiers JS/CSS avec hash
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers pour le manifest et favicon
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Configuration des formulaires Netlify (si nécessaire)
[forms]
  # Activer les formulaires Netlify
  spam_protection = true

# Configuration du déploiement continu
[context.production]
  command = "npm run build"
  environment = { NODE_ENV = "production", GENERATE_SOURCEMAP = "false" }

[context.deploy-preview]
  command = "npm run build"
  environment = { NODE_ENV = "production", GENERATE_SOURCEMAP = "true" }

[context.branch-deploy]
  command = "npm run build"

# Configuration des fonctions Netlify (si nécessaire plus tard)
[functions]
  directory = "netlify/functions"

# Configuration des plugins Netlify
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.audits]
    performance = true
    accessibility = true
    best-practices = true
    seo = true

[[plugins]]
  package = "netlify-plugin-html-validate"

# Variables d'environnement (à configurer dans l'interface Netlify)
# REACT_APP_API_URL = "https://your-api-domain.com"
# REACT_APP_ENV = "production"